import type { ConditioningFocus } from '../../types';

export type MuscleRegion = 'chest' | 'abs' | 'shoulders' | 'arms' | 'legs' | 'back';

/**
 * Exercise catalog. `equipment` and `instructions` (Spanish "cómo se hace") are optional and were
 * enriched from the open exercises-dataset (hasaneyldrm/exercises-dataset, instruction text MIT).
 * Media/GIFs from that dataset are NOT used (© Gym visual, requires separate license).
 */
export interface CatalogExercise {
  name: string;
  focus: ConditioningFocus;
  muscles: MuscleRegion[];
  /** Equipo principal en español (ej. "Barra", "Mancuerna"). Opcional. */
  equipment?: string;
  /** Instrucción paso a paso en español. Opcional. */
  instructions?: string;
}

export const EXERCISE_CATALOG: CatalogExercise[] = [
  // PECHO
  { name: 'Press de banca con barra', focus: 'PECHO', muscles: ['chest', 'shoulders', 'arms'], equipment: 'Barra', instructions: 'Túmbate sobre un banco con los pies apoyados en el suelo y la espalda presionada contra el banco. Agarra la barra con un agarre pronado un poco más ancho que la separación de los hombros. Levanta la barra del soporte y sostenla directamente sobre el pecho con los brazos completamente extendidos. Baja la barra lentamente hacia el pecho, manteniendo los codos pegados al cuerpo. Haz una pausa breve cuando la barra toque el pecho. Empuja la barra de vuelta a la posición inicial extendiendo los brazos. Repite el número de repeticiones deseado.' },
  { name: 'Press inclinado con barra', focus: 'PECHO', muscles: ['chest', 'shoulders', 'arms'], equipment: 'Barra', instructions: 'Coloca un banco inclinado a un ángulo de 45 grados. Túmbate en el banco con los pies planos sobre el suelo. Agarra la barra con un agarre pronado un poco más ancho que la separación de los hombros. Saca la barra del soporte y bájala lentamente hacia el pecho, manteniendo los codos a un ángulo de 45 grados. Haz una pausa breve en la parte baja y luego empuja la barra de vuelta a la posición inicial. Repite el número de repeticiones deseado.' },
  { name: 'Press con mancuernas', focus: 'PECHO', muscles: ['chest', 'shoulders', 'arms'], equipment: 'Mancuerna', instructions: 'Túmbate sobre un banco con los pies apoyados en el suelo y la espalda presionada contra el banco. Sujeta una mancuerna en cada mano, con las palmas hacia adelante y los brazos extendidos por encima del pecho. Baja lentamente las mancuernas hacia los lados del pecho, manteniendo los codos en un ángulo de 90 grados. Haz una pausa breve, luego empuja las mancuernas de vuelta hacia arriba hasta la posición inicial, extendiendo completamente los brazos. Repite el número de repeticiones deseado.' },
  { name: 'Press inclinado con mancuernas', focus: 'PECHO', muscles: ['chest', 'shoulders', 'arms'], equipment: 'Mancuerna', instructions: 'Coloca un banco inclinado a un ángulo de 45 grados. Siéntate en el banco con los pies apoyados en el suelo y la espalda firmemente apoyada contra el banco. Sostén una mancuerna en cada mano, con las palmas hacia adelante, y levántalas hasta la altura de los hombros. Baja lentamente las mancuernas hacia los lados del pecho, manteniendo los codos en un ángulo de 90 grados. Empuja las mancuernas de nuevo hacia arriba hasta la posición inicial, extendiendo completamente los brazos. Repite el número de repeticiones deseado.' },
  { name: 'Aperturas con mancuernas', focus: 'PECHO', muscles: ['chest'], equipment: 'Mancuerna', instructions: 'Túmbate boca arriba en un banco con una mancuerna en cada mano, con las palmas enfrentadas entre sí. Extiende los brazos rectos hacia arriba sobre el pecho, con una ligera flexión en los codos. Manteniendo una ligera flexión en los codos, baja los brazos hacia los lados en un amplio arco hasta sentir un estiramiento en el pecho. Haz una pausa por un momento, luego invierte el movimiento y lleva las mancuernas de nuevo hacia arriba hasta la posición inicial. Repite el número de repeticiones deseado.' },
  { name: 'Fondos en paralelas', focus: 'PECHO', muscles: ['chest', 'arms', 'shoulders'], equipment: 'Peso corporal', instructions: 'Colócate en las barras paralelas con los brazos completamente extendidos y el cuerpo recto. Baja el cuerpo flexionando los codos hasta que los hombros queden por debajo de los codos. Empújate de vuelta hacia arriba a la posición inicial extendiendo los brazos. Repite el número de repeticiones deseado.' },
  { name: 'Pec deck (contractor)', focus: 'PECHO', muscles: ['chest'], equipment: 'Máquina', instructions: 'Ajusta la altura del asiento y colócate en la máquina con la espalda apoyada en la almohadilla. Agarra las asas con un agarre pronado y mantén los codos ligeramente flexionados. Exhala y empuja las asas hacia adelante, juntándolas frente a tu pecho. Haz una pausa por un momento, contrayendo los músculos del pecho. Inhala y vuelve lentamente a la posición inicial, permitiendo que los músculos del pecho se estiren. Repite el número de repeticiones deseado.' },
  { name: 'Cruces en polea', focus: 'PECHO', muscles: ['chest'], equipment: 'Polea', instructions: 'Ajusta las poleas del cable a la altura del pecho. Ponte de pie en el centro de la máquina de cable con un pie delante del otro. Sujeta las agarraderas con las palmas hacia abajo y los brazos extendidos hacia los lados. Da un paso hacia adelante, manteniendo los brazos ligeramente flexionados. Con una ligera flexión en los codos, junta las manos frente al pecho. Haz una pausa breve, luego vuelve lentamente los brazos a la posición inicial. Repite el número de repeticiones deseado.' },
  // ESPALDA
  { name: 'Dominadas', focus: 'ESPALDA', muscles: ['back', 'arms'], equipment: 'Peso corporal', instructions: 'Cuélgate de una barra de dominadas con las palmas hacia afuera y los brazos completamente extendidos. Activa el core y junta los omóplatos. Tira de tu cuerpo hacia la barra flexionando los codos y llevando el pecho hacia la barra. Haz una pausa en la parte alta del movimiento y luego baja lentamente el cuerpo de vuelta a la posición inicial. Repite el número de repeticiones deseado.' },
  { name: 'Jalón al pecho', focus: 'ESPALDA', muscles: ['back', 'arms'], equipment: 'Polea', instructions: 'Siéntate en la máquina de jalón al pecho con las rodillas colocadas debajo de las almohadillas. Sujeta la barra del cable con un agarre prono, un poco más separado que el ancho de los hombros. Inclínate ligeramente hacia atrás y mantén el pecho elevado, conservando un ligero arco en la zona lumbar. Jala la barra hacia la parte superior del pecho, apretando los omóplatos entre sí. Haz una pausa por un momento en la parte baja del movimiento y luego suelta lentamente la barra de vuelta a la posición inicial. Repite el número de repeticiones deseado.' },
  { name: 'Remo con barra', focus: 'ESPALDA', muscles: ['back', 'arms'], equipment: 'Barra', instructions: 'Ponte de pie con los pies separados a la altura de los hombros y las rodillas ligeramente flexionadas. Inclínate hacia delante desde las caderas manteniendo la espalda recta y el pecho elevado. Agarra la barra con un agarre pronado, con las manos un poco más separadas que el ancho de los hombros. Tira de la barra hacia la parte inferior del pecho retrayendo los omóplatos y contrayendo los músculos de la espalda. Haz una pausa breve en la parte alta y luego baja lentamente la barra de vuelta a la posición inicial. Repite el número de repeticiones deseado.' },
  { name: 'Remo con mancuerna', focus: 'ESPALDA', muscles: ['back', 'arms'], equipment: 'Mancuerna', instructions: 'Ponte de pie con los pies separados a la altura de los hombros, las rodillas ligeramente flexionadas, y sujeta una mancuerna en cada mano con las palmas hacia tu cuerpo. Inclínate hacia adelante desde las caderas, manteniendo la espalda recta y el core activado. Deja que los brazos cuelguen rectos hacia el suelo, con los codos ligeramente flexionados. Tira de las mancuernas hacia arriba, hacia el pecho, apretando los omóplatos entre sí. Haz una pausa breve en la parte alta, luego baja lentamente las mancuernas de vuelta a la posición inicial. Repite el número de repeticiones deseado.' },
  { name: 'Remo en polea baja', focus: 'ESPALDA', muscles: ['back', 'arms'], equipment: 'Polea', instructions: 'Siéntate en la máquina de remo con cable con los pies planos sobre los apoyapiés y las rodillas ligeramente flexionadas. Sujeta las agarraderas con un agarre prono, manteniendo la espalda recta y los hombros relajados. Jala las agarraderas hacia el cuerpo, apretando los omóplatos entre sí. Haz una pausa por un momento en el punto máximo del movimiento, luego suelta lentamente las agarraderas de vuelta a la posición inicial. Repite el número de repeticiones deseado.' },
  { name: 'Peso muerto', focus: 'ESPALDA', muscles: ['back', 'legs'], equipment: 'Barra', instructions: 'Ponte de pie con los pies separados a la altura de los hombros y la barra en el suelo frente a ti. Flexiona las rodillas y las caderas para bajar el torso y agarra la barra con un agarre pronado, con las manos un poco más separadas que el ancho de los hombros. Mantén la espalda recta y el pecho elevado mientras empujas con los talones para levantar la barra del suelo, extendiendo las caderas y las rodillas. Al ponerte de pie, aprieta los glúteos y mantén el core activado. Baja la barra de vuelta al suelo flexionando las caderas y las rodillas, manteniendo la espalda recta. Repite el número de repeticiones deseado.' },
  { name: 'Pull-over', focus: 'ESPALDA', muscles: ['back', 'chest'], equipment: 'Mancuerna', instructions: 'Túmbate boca arriba en un banco con la cabeza en un extremo y los pies en el suelo. Sujeta una mancuerna con ambas manos y extiende los brazos rectos por encima del pecho. Manteniendo una ligera flexión en los codos, baja lentamente la mancuerna detrás de la cabeza hasta sentir un estiramiento en el pecho y los hombros. Haz una pausa por un momento, luego levanta la mancuerna de vuelta a la posición inicial. Repite el número de repeticiones deseado.' },
  { name: 'Face pull', focus: 'ESPALDA', muscles: ['shoulders', 'back'] },
  // HOMBRO
  { name: 'Press militar con barra', focus: 'HOMBRO', muscles: ['shoulders', 'arms'], equipment: 'Barra', instructions: 'Siéntate en un banco con la espalda recta y los pies planos sobre el suelo. Sujeta la barra con un agarre pronado, un poco más ancho que la separación de los hombros. Levanta la barra del soporte y llévala a la altura de los hombros, con los codos flexionados y las palmas hacia delante. Empuja la barra por encima de la cabeza extendiendo completamente los brazos. Haz una pausa breve en la parte alta y luego baja lentamente la barra de vuelta a la altura de los hombros. Repite el número de repeticiones deseado.' },
  { name: 'Press Arnold', focus: 'HOMBRO', muscles: ['shoulders', 'arms'], equipment: 'Mancuerna', instructions: 'Siéntate en un banco con respaldo y sujeta una mancuerna en cada mano a la altura del hombro, con las palmas hacia tu cuerpo y los codos flexionados. Empuja las mancuernas hacia arriba hasta que los brazos estén completamente extendidos y las palmas miren hacia adelante. Rota las muñecas mientras levantas, de modo que las palmas miren hacia adelante en la parte alta del movimiento. Haz una pausa breve en la parte alta, luego baja lentamente las mancuernas de vuelta a la posición inicial. Repite el número de repeticiones deseado.' },
  { name: 'Elevaciones laterales', focus: 'HOMBRO', muscles: ['shoulders'], equipment: 'Mancuerna', instructions: 'Ponte de pie con los pies separados a la altura de los hombros y sostén una mancuerna en cada mano, con las palmas hacia el cuerpo. Mantén la espalda recta y activa el core. Levanta los brazos hacia los lados hasta que queden paralelos al suelo, manteniendo una ligera flexión en los codos. Haz una pausa por un momento en la parte superior, luego baja lentamente los brazos de vuelta a la posición inicial. Repite el número de repeticiones deseado.' },
  { name: 'Elevaciones frontales', focus: 'HOMBRO', muscles: ['shoulders'], equipment: 'Mancuerna', instructions: 'Ponte de pie con los pies separados a la altura de los hombros, sosteniendo una mancuerna en cada mano con las palmas hacia los muslos. Manteniendo los brazos rectos, exhala y levanta las mancuernas frente a ti hasta que queden a la altura de los hombros. Haz una pausa por un momento en la parte superior, luego inhala y baja lentamente las mancuernas de vuelta a la posición inicial. Repite el número de repeticiones deseado.' },
  { name: 'Pájaros (deltoide posterior)', focus: 'HOMBRO', muscles: ['shoulders', 'back'], equipment: 'Mancuerna', instructions: 'Ponte de pie con los pies separados a la altura de los hombros y sostén una mancuerna en cada mano. Flexiona ligeramente las rodillas e inclínate hacia adelante desde las caderas, manteniendo la espalda recta. Extiende los brazos rectos hacia adelante, con las palmas mirándose entre sí. Manteniendo una ligera flexión en los codos, levanta los brazos hacia los lados hasta que queden paralelos al suelo. Haz una pausa por un momento en la parte superior, luego baja lentamente los brazos de vuelta a la posición inicial. Repite el número de repeticiones deseado.' },
  { name: 'Encogimientos (trapecio)', focus: 'HOMBRO', muscles: ['back', 'shoulders'], equipment: 'Mancuerna', instructions: 'Ponte de pie con los pies separados a la altura de los hombros y sujeta una mancuerna en cada mano con las palmas hacia tu cuerpo. Mantén los brazos rectos y deja que las mancuernas cuelguen a tus costados. Eleva los hombros lo más alto posible, como si intentaras tocarte las orejas con ellos. Mantén la contracción durante un segundo, luego baja lentamente los hombros de vuelta a la posición inicial. Repite el número de repeticiones deseado.' },
  // BRAZO
  { name: 'Curl con barra', focus: 'BRAZO', muscles: ['arms'], equipment: 'Barra', instructions: 'Ponte de pie con los pies separados a la altura de los hombros y sujeta una barra con un agarre supino, con las palmas mirando hacia delante. Mantén los codos cerca del torso y exhala mientras levantas el peso contrayendo los bíceps. Continúa levantando la barra hasta que los bíceps estén completamente contraídos y la barra esté a la altura de los hombros. Mantén la posición contraída durante una breve pausa mientras aprietas los bíceps. Inhala mientras comienzas a bajar lentamente la barra de vuelta a la posición inicial. Repite el número de repeticiones deseado.' },
  { name: 'Curl con mancuernas', focus: 'BRAZO', muscles: ['arms'], equipment: 'Mancuerna', instructions: 'Ponte de pie con una mancuerna en cada mano, con las palmas hacia adelante y los brazos completamente extendidos. Manteniendo los brazos superiores fijos, exhala y levanta el peso mientras contraes los bíceps. Continúa levantando las pesas hasta que los bíceps estén completamente contraídos y las mancuernas estén a la altura de los hombros. Mantén la posición contraída durante una breve pausa mientras aprietas los bíceps. Inhala y comienza a bajar lentamente las mancuernas de vuelta a la posición inicial. Repite el número de repeticiones deseado.' },
  { name: 'Curl martillo', focus: 'BRAZO', muscles: ['arms'], equipment: 'Mancuerna', instructions: 'Ponte de pie con una mancuerna en cada mano, con las palmas mirando hacia el torso. Mantén los codos cerca del torso y gira las palmas de las manos hasta que queden mirando hacia adelante. Esta será tu posición inicial. Ahora, manteniendo los brazos superiores quietos, exhala y flexiona los brazos contrayendo los bíceps. Continúa levantando las pesas hasta que los bíceps estén completamente contraídos y las mancuernas estén a la altura de los hombros. Mantén la posición contraída durante una breve pausa mientras aprietas los bíceps. Luego, inhala y comienza a bajar lentamente las mancuernas de vuelta a la posición inicial. Repite el número de repeticiones recomendado.' },
  { name: 'Curl predicador', focus: 'BRAZO', muscles: ['arms'], equipment: 'Barra', instructions: 'Siéntate en un banco predicador con los brazos superiores apoyados en el cojín y el pecho contra el soporte. Agarra la barra con un agarre supino, un poco más ancho que la separación de los hombros. Manteniendo los brazos superiores fijos, exhala y levanta la barra hacia los hombros. Haz una pausa breve en la parte alta, apretando los bíceps. Inhala y baja lentamente la barra de vuelta a la posición inicial. Repite el número de repeticiones deseado.' },
  { name: 'Press francés', focus: 'BRAZO', muscles: ['arms'], equipment: 'Barra', instructions: 'Túmbate boca arriba en un banco con los pies planos sobre el suelo y la cabeza en el extremo del banco. Sujeta una barra con un agarre pronado, manos separadas a la altura de los hombros, y extiende los brazos rectos por encima del pecho. Manteniendo los brazos superiores fijos, baja lentamente la barra hacia la frente flexionando los codos. Haz una pausa breve en la parte baja y luego extiende los brazos de vuelta a la posición inicial. Repite el número de repeticiones deseado.' },
  { name: 'Extensión de tríceps en polea', focus: 'BRAZO', muscles: ['arms'], equipment: 'Polea', instructions: 'Coloca un accesorio en V en la máquina de cable en el ajuste más alto. Ponte de pie frente a la máquina de cable con los pies separados a la altura de los hombros. Agarra el accesorio en V con un agarre prono, con las palmas hacia abajo y las manos separadas a la altura de los hombros. Mantén los codos cerca de los costados y los brazos superiores quietos durante todo el ejercicio. Activa los tríceps y exhala mientras empujas el accesorio en V hacia abajo hasta que los brazos estén completamente extendidos. Haz una pausa breve en la parte baja del movimiento, apretando los tríceps. Inhala mientras regresas lentamente el accesorio en V a la posición inicial, manteniendo el control. Repite el número de repeticiones deseado.' },
  { name: 'Fondos en banco', focus: 'BRAZO', muscles: ['arms', 'chest'], equipment: 'Peso corporal', instructions: 'Siéntate en el borde de un banco o silla con las manos sujetando el borde junto a las caderas. Desliza los glúteos fuera del banco y estira las piernas frente a ti, manteniendo los talones en el suelo. Flexiona los codos y baja el cuerpo hacia el suelo, manteniendo la espalda cerca del banco. Haz una pausa por un momento en la parte inferior, luego empuja tu cuerpo de vuelta a la posición inicial. Repite el número de repeticiones deseado.' },
  // PIERNA
  { name: 'Sentadilla con barra', focus: 'PIERNA', muscles: ['legs', 'back', 'abs'], equipment: 'Barra', instructions: 'Ponte de pie con los pies separados a la altura de los hombros, con los dedos de los pies ligeramente hacia afuera. Sujeta la barra sobre la parte superior de la espalda, apoyándola en los trapecios o los deltoides posteriores. Activa el core y mantén el pecho elevado mientras comienzas a bajar el cuerpo. Flexiona las rodillas y las caderas, empujando las caderas hacia atrás y hacia abajo como si te sentaras en una silla. Baja hasta que los muslos queden paralelos al suelo o un poco por debajo. Mantén las rodillas alineadas con los dedos de los pies y el peso sobre los talones. Empuja con los talones para volver a ponerte de pie, extendiendo las caderas y las rodillas. Repite el número de repeticiones deseado.' },
  { name: 'Prensa de pierna', focus: 'PIERNA', muscles: ['legs'], equipment: 'Máquina', instructions: 'Ajusta el asiento y la plataforma para los pies de la máquina de palanca a la posición deseada. Siéntate en la máquina con la espalda apoyada en el respaldo y los pies sobre la plataforma para los pies. Coloca las manos en las asas o en los lados de la máquina para mayor estabilidad. Empuja un pie contra la plataforma para los pies, extendiendo la pierna hasta que esté casi completamente recta. Haz una pausa breve, luego flexiona lentamente la pierna y vuelve a la posición inicial. Repite con la otra pierna. Continúa alternando las piernas durante el número de repeticiones deseado.' },
  { name: 'Peso muerto rumano', focus: 'PIERNA', muscles: ['legs', 'back'], equipment: 'Barra', instructions: 'Ponte de pie con los pies separados a la altura de los hombros y los dedos de los pies apuntando hacia delante. Sujeta la barra con un agarre pronado, manos un poco más separadas que el ancho de los hombros. Flexiona las caderas, manteniendo la espalda recta y las rodillas ligeramente flexionadas. Baja la barra hacia el suelo, manteniéndola cerca del cuerpo. Siente el estiramiento en los isquiotibiales mientras bajas la barra. Cuando sientas el estiramiento en los isquiotibiales, empuja las caderas hacia delante y ponte de pie. Aprieta los glúteos en la parte alta del movimiento. Baja la barra de vuelta a la posición inicial y repite el número de repeticiones deseado.' },
  { name: 'Zancadas', focus: 'PIERNA', muscles: ['legs', 'abs'], equipment: 'Barra', instructions: 'Empieza de pie con los pies separados a la altura de los hombros y una barra apoyada sobre la parte superior de la espalda. Da un paso hacia delante con el pie derecho, manteniendo el torso erguido. Baja el cuerpo flexionando la rodilla derecha hasta que el muslo quede paralelo al suelo. Empuja con el talón derecho para regresar a la posición inicial. Repite con la pierna izquierda, alternando las piernas el número de repeticiones deseado.' },
  { name: 'Extensión de cuádriceps', focus: 'PIERNA', muscles: ['legs'], equipment: 'Máquina', instructions: 'Ajusta la altura del asiento y el respaldo de la máquina a tu cuerpo. Siéntate en la máquina con la espalda apoyada en el respaldo y los pies sobre la almohadilla para los pies. Sujeta las asas o las barras laterales para mayor estabilidad. Extiende las piernas hacia adelante enderezando las rodillas, levantando el peso. Haz una pausa breve en lo alto, luego baja lentamente el peso de vuelta a la posición inicial. Repite el número de repeticiones deseado.' },
  { name: 'Curl femoral', focus: 'PIERNA', muscles: ['legs'], equipment: 'Máquina', instructions: 'Ajusta la máquina a tu cuerpo y selecciona el peso deseado. Arrodíllate en la máquina mirando hacia abajo, con las rodillas apoyadas en la almohadilla y los pies asegurados bajo las almohadillas para los pies. Sujeta las asas o los lados de la máquina para mayor estabilidad. Manteniendo quieta la parte superior del cuerpo, exhala y flexiona las piernas hacia los glúteos doblando las rodillas. Haz una pausa breve en la parte más alta del movimiento, contrayendo los isquiotibiales. Inhala y baja lentamente las piernas de vuelta a la posición inicial, extendiendo por completo las rodillas. Repite el número de repeticiones deseado.' },
  { name: 'Hip thrust', focus: 'PIERNA', muscles: ['legs', 'abs'] },
  { name: 'Elevación de gemelos', focus: 'PIERNA', muscles: ['legs'], equipment: 'Máquina', instructions: 'Ajusta la máquina a tu altura y ponte de pie con los pies separados a la altura de los hombros. Coloca los hombros debajo de las almohadillas y sujétate de las asas para mayor estabilidad. Eleva los talones tan alto como puedas extendiendo los tobillos. Haz una pausa breve en la parte alta y luego baja lentamente los talones de vuelta a la posición inicial. Repite el número de repeticiones deseado.' },
  { name: 'Sentadilla búlgara', focus: 'PIERNA', muscles: ['legs'], equipment: 'Barra', instructions: 'Ponte de pie con los pies separados a la altura de los hombros, sujetando una barra sobre la parte superior de la espalda. Da un paso grande hacia adelante con una pierna, manteniendo el torso erguido. Baja el cuerpo flexionando la rodilla delantera y la cadera, mientras mantienes la pierna trasera recta. Continúa bajando hasta que el muslo delantero quede paralelo al suelo. Haz una pausa breve, luego empuja con el talón delantero para volver a la posición inicial. Repite el número de repeticiones deseado, luego cambia de pierna.' },
  // CORE
  { name: 'Plancha', focus: 'CORE', muscles: ['abs', 'shoulders', 'arms'] },
  { name: 'Abdominales (crunch)', focus: 'CORE', muscles: ['abs'], equipment: 'Peso corporal', instructions: 'Túmbate sobre tu espalda con las rodillas flexionadas y los pies apoyados en el suelo. Coloca las manos detrás de la cabeza con los codos apuntando hacia afuera. Activa el abdomen y levanta los hombros del suelo, flexionándote hacia adelante en dirección a las rodillas. Haz una pausa breve en la parte alta, luego baja lentamente los hombros de vuelta a la posición inicial. Repite el número de repeticiones deseado.' },
  { name: 'Elevación de piernas', focus: 'CORE', muscles: ['abs'], equipment: 'Peso corporal', instructions: 'Cuélgate de una barra de dominadas con los brazos completamente extendidos y las palmas mirando hacia afuera. Activa el core y levanta las piernas frente a ti, manteniéndolas rectas. Continúa levantando hasta que las piernas estén paralelas al suelo o tan alto como puedas llegar cómodamente. Haz una pausa por un momento en la parte superior, luego baja lentamente las piernas de vuelta a la posición inicial. Repite el número de repeticiones deseado.' },
  { name: 'Russian twist', focus: 'CORE', muscles: ['abs'], equipment: 'Peso corporal', instructions: 'Siéntate en el suelo con las rodillas flexionadas y los pies apoyados en el suelo. Inclínate ligeramente hacia atrás manteniendo la espalda recta y el core activado. Junta las manos frente al pecho o sujeta una pesa si lo deseas. Levanta los pies del suelo, equilibrándote sobre los isquiones. Gira el torso hacia la derecha, llevando las manos o la pesa hacia el lado derecho del cuerpo. Haz una pausa por un momento, luego gira el torso hacia la izquierda, llevando las manos o la pesa hacia el lado izquierdo del cuerpo. Continúa alternando lados durante el número de repeticiones deseado.' },
  { name: 'Rueda abdominal', focus: 'CORE', muscles: ['abs', 'arms', 'shoulders'], equipment: 'Rueda abdominal', instructions: 'Comienza de pie, erguido, con los pies separados a la altura de los hombros y el rodillo frente a ti. Dobla la cintura y haz rodar lentamente el rodillo hacia adelante, manteniendo la espalda recta y el core activado. Continúa rodando hacia adelante hasta sentir un estiramiento en el abdomen y que tu cuerpo esté extendido lo máximo posible. Haz una pausa de un momento, luego haz rodar lentamente el rodillo de regreso hacia tu cuerpo, volviendo a la posición inicial. Repite el número de repeticiones deseado.' },
  { name: 'Plancha lateral', focus: 'CORE', muscles: ['abs'], equipment: 'Peso corporal', instructions: 'Comienza tumbado de lado con las piernas extendidas y apiladas una sobre la otra. Coloca el antebrazo en el suelo justo debajo del hombro, con el codo flexionado en un ángulo de 90 grados. Activa el core y levanta las caderas del suelo, formando una línea recta desde la cabeza hasta los pies. Mantén esta posición durante el tiempo deseado. Baja las caderas de nuevo al suelo y repite hacia el otro lado.' },
  // CARDIO
  { name: 'Trote', focus: 'CARDIO', muscles: ['legs', 'abs'], equipment: 'Peso corporal', instructions: 'Comienza de pie con los pies separados a la altura de la cadera. Activa el core y mantén la parte superior del cuerpo relajada. Comienza a trotar en el lugar, levantando las rodillas hacia el pecho y aterrizando suavemente sobre la punta de los pies. Mantén un ritmo constante y continúa trotando durante la duración o distancia deseada. Recuerda respirar profundamente y mantener una buena postura durante todo el ejercicio.' },
  { name: 'Bicicleta', focus: 'CARDIO', muscles: ['legs'], equipment: 'Bicicleta estática', instructions: 'Ajusta la altura y la posición del asiento para asegurar una alineación correcta. Coloca los pies sobre los pedales y sujétalos con las correas si están disponibles. Comienza a pedalear a un ritmo cómodo. Mantén un ritmo constante y aumenta la resistencia según lo desees. Activa los músculos del core para mantener la estabilidad y una postura correcta. Continúa pedaleando durante la duración deseada de tu entrenamiento. Disminuye gradualmente la resistencia y reduce la velocidad antes de detenerte por completo. Estira las piernas y enfría después del entrenamiento.' },
  { name: 'Elíptica', focus: 'CARDIO', muscles: ['legs', 'arms'], equipment: 'Elíptica', instructions: 'Ajusta el nivel de resistencia y la inclinación de la máquina elíptica a los valores deseados. Sube a los pedales de la máquina y agarra las asas con suavidad. Comienza empujando hacia abajo con los pies y tirando de las asas hacia tu cuerpo. Continúa con este movimiento, alternando entre empujar y tirar, para simular un movimiento de caminar o correr. Mantén un ritmo constante y conserva el core activado durante todo el ejercicio. Continúa durante la duración deseada de tu entrenamiento cardiovascular. Disminuye gradualmente la intensidad y la velocidad de la máquina antes de bajarte.' },
  { name: 'Saltar la cuerda', focus: 'CARDIO', muscles: ['legs', 'arms'], equipment: 'Cuerda', instructions: 'Sujeta las asas de la cuerda de saltar con las manos, palmas hacia adentro. Ponte de pie con los pies separados a la altura de los hombros y las rodillas ligeramente flexionadas. Balancea la cuerda por encima de la cabeza y salta sobre ella cuando se acerque a los pies. Aterriza suavemente sobre la punta de los pies y repite el salto cuando la cuerda vuelva a pasar. Continúa saltando durante el tiempo o el número de repeticiones deseado.' },
  { name: 'Remo (máquina)', focus: 'CARDIO', muscles: ['back', 'arms', 'legs'] },
  { name: 'Escaladora', focus: 'CARDIO', muscles: ['legs', 'arms', 'abs'] },
  // FULL_BODY
  { name: 'Burpees', focus: 'FULL_BODY', muscles: ['chest', 'arms', 'legs', 'abs', 'shoulders'], equipment: 'Peso corporal', instructions: 'Comienza de pie con los pies separados a la altura de los hombros. Baja el cuerpo hacia una posición de sentadilla flexionando las rodillas y colocando las manos en el suelo frente a ti. Lleva los pies hacia atrás de una patada hasta una posición de flexión de brazos. Realiza una flexión de brazos, manteniendo el cuerpo en línea recta. Salta con los pies de vuelta a la posición de sentadilla. Salta hacia arriba explosivamente, llevando los brazos por encima de la cabeza. Aterriza suavemente y baja de inmediato a una posición de sentadilla para comenzar la siguiente repetición.' },
  { name: 'Thrusters', focus: 'FULL_BODY', muscles: ['legs', 'shoulders', 'arms'], equipment: 'Barra', instructions: 'Comienza de pie con los pies separados a la altura de los hombros, sujetando una barra a la altura de los hombros con agarre prono. Baja a una posición de sentadilla flexionando las rodillas y empujando las caderas hacia atrás. Al llegar a la parte más baja de la sentadilla, empuja explosivamente con los talones para ponerte de pie, presionando simultáneamente la barra por encima de la cabeza. Baja la barra de nuevo a la altura de los hombros mientras vuelves a bajar a la posición de sentadilla. Repite el número de repeticiones deseado.' },
  { name: 'Kettlebell swing', focus: 'FULL_BODY', muscles: ['back', 'legs', 'abs'], equipment: 'Kettlebell', instructions: 'Ponte de pie con los pies separados a la altura de los hombros, con los dedos de los pies ligeramente hacia afuera. Sujeta la pesa rusa con ambas manos frente al cuerpo, con los brazos extendidos. Flexiona ligeramente las rodillas e inclínate desde las caderas, empujando los glúteos hacia atrás. Lleva la pesa rusa hacia atrás entre las piernas, manteniendo los brazos rectos y la espalda plana. Lleva las caderas hacia adelante y haz que la pesa rusa suba hasta la altura del hombro, usando el impulso generado por las caderas. Deja que la pesa rusa se balancee de vuelta hacia abajo entre las piernas y repite el movimiento el número de repeticiones deseado.' },
  { name: 'Clean and press', focus: 'FULL_BODY', muscles: ['shoulders', 'back', 'legs', 'arms'], equipment: 'Barra', instructions: 'Ponte de pie con los pies separados a la altura de los hombros y la barra en el suelo frente a ti. Flexiona las rodillas y las caderas para bajar y agarrar la barra con un agarre pronado, con las manos un poco más separadas que el ancho de los hombros. Empuja con los talones y extiende las caderas y las rodillas para levantar la barra del suelo, manteniéndola cerca del cuerpo. Cuando la barra llegue a los muslos, extiende las caderas de forma explosiva, encoge los hombros y tira de la barra hacia el pecho. Cuando la barra llegue a la altura del pecho, baja rápidamente debajo de ella y atrápala a la altura de los hombros, con los codos apuntando hacia delante y las palmas hacia arriba. Desde la posición de recepción, empuja la barra por encima de la cabeza extendiendo los brazos y llevando la barra recta hacia arriba. Baja la barra de vuelta a la posición inicial y repite el número de repeticiones deseado.' },
  { name: 'Snatch con mancuerna', focus: 'FULL_BODY', muscles: ['shoulders', 'back', 'legs', 'arms'], equipment: 'Mancuerna', instructions: 'Ponte de pie con los pies separados a la altura de los hombros, sosteniendo una mancuerna en una mano con agarre prono. Flexiona ligeramente las rodillas e inclínate hacia adelante desde las caderas, manteniendo la espalda recta y el pecho elevado. Baja la mancuerna hacia el suelo, manteniéndola cerca del cuerpo. Extiende explosivamente las caderas, las rodillas y los tobillos, impulsando la mancuerna hacia arriba en línea recta. Cuando la mancuerna alcance la altura del hombro, gira rápidamente la mano y empújala por encima de la cabeza, extendiendo completamente el brazo. Recibe la mancuerna por encima de la cabeza con una ligera flexión en las rodillas y las caderas. Baja la mancuerna de nuevo a la posición inicial de manera controlada. Repite el número de repeticiones deseado, luego cambia al otro brazo.' },
];

/** Build a lookup map for O(1) muscle resolution by name (lowercase). */
const CATALOG_MAP = new Map(EXERCISE_CATALOG.map((e) => [e.name.toLowerCase(), e.muscles]));

/** Full-entry lookup by name (lowercase) — for equipment + "cómo se hace" in the form. */
const CATALOG_INFO = new Map(EXERCISE_CATALOG.map((e) => [e.name.toLowerCase(), e]));

/** Returns the catalog entry for an exact (case-insensitive) exercise name, or null. */
export function getExerciseInfo(name: string): CatalogExercise | null {
  return CATALOG_INFO.get(name.trim().toLowerCase()) ?? null;
}

const FOCUS_MUSCLES: Record<ConditioningFocus, MuscleRegion[]> = {
  PECHO:     ['chest'],
  ESPALDA:   ['back'],
  HOMBRO:    ['shoulders'],
  BRAZO:     ['arms'],
  PIERNA:    ['legs'],
  CORE:      ['abs'],
  CARDIO:    ['chest', 'abs', 'arms', 'legs', 'shoulders', 'back'],
  FULL_BODY: ['chest', 'abs', 'arms', 'legs', 'shoulders', 'back'],
};

/**
 * Returns the union of muscles for a list of exercise names.
 * Names not in the catalog are silently ignored.
 */
export function getMusclesFromNames(names: string[]): MuscleRegion[] {
  const out = new Set<MuscleRegion>();
  for (const name of names) {
    const muscles = CATALOG_MAP.get(name.trim().toLowerCase());
    if (muscles) muscles.forEach((m) => out.add(m));
  }
  return [...out];
}

/**
 * Returns muscles for a focus chip — used as fallback when no exercise names are known.
 */
export function getMusclesFromFocus(focus: ConditioningFocus | null): MuscleRegion[] {
  return focus ? FOCUS_MUSCLES[focus] : [];
}

/**
 * Suggestions for the exercise name input: the student's recent names first, then catalog
 * entries for the chosen focus, then the rest. Filtered by the typed query, deduped, capped.
 */
export function suggestExercises(query: string, focus: ConditioningFocus | null, recents: string[], limit = 8): string[] {
  const q = query.trim().toLowerCase();
  const ordered = [
    ...recents,
    ...EXERCISE_CATALOG.filter((e) => focus && e.focus === focus).map((e) => e.name),
    ...EXERCISE_CATALOG.map((e) => e.name),
  ];
  const seen = new Set<string>();
  const out: string[] = [];
  for (const name of ordered) {
    const key = name.toLowerCase();
    if (seen.has(key)) continue;
    if (key === q) continue;
    if (q && !key.includes(q)) continue;
    seen.add(key);
    out.push(name);
    if (out.length >= limit) break;
  }
  return out;
}
